# Generated by Django 5.2.4 on 2025-07-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='biografia',
        ),
    ]
