# Generated by Django 5.2.1 on 2025-06-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='dias_semana',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
