# Generated by Django 5.2.4 on 2025-07-13 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_actividad_dias_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='icono',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='registrohabito',
            name='habito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='activities.actividad'),
        ),
    ]
