# Generated by Django 5.2.4 on 2025-07-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_actividad_icono_alter_registrohabito_habito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='icono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
