# Generated by Django 5.2.4 on 2025-07-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_actividad_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='meta_tipo',
            field=models.CharField(blank=True, choices=[('dias', 'Días'), ('meses', 'Meses'), ('fecha_limite', 'Fecha límite')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='meta_valor',
            field=models.PositiveIntegerField(blank=True, help_text='Número de días o meses', null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='icono',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
