# Generated by Django 5.2.4 on 2025-07-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_actividad_meta_tipo_actividad_meta_valor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='meta_tipo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='meta_valor',
        ),
        migrations.AddField(
            model_name='actividad',
            name='meta_dias',
            field=models.PositiveIntegerField(blank=True, default=150, help_text='Número de días meta para completar este hábito', null=True),
        ),
    ]
