# Generated by Django 5.2.3 on 2025-07-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_remove_actividad_meta_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='meta_tipo',
            field=models.CharField(blank=True, choices=[('dias', 'Días'), ('semanas', 'Semanas'), ('meses', 'Meses')], default='dias', help_text='Tipo de meta (días, semanas, meses)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='meta_valor',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Valor de la meta (ej: 30 días, 12 semanas, 6 meses)', null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='meta_dias',
            field=models.PositiveIntegerField(blank=True, default=150, help_text='Número de días meta para completar este hábito (legacy)', null=True),
        ),
    ]
