# Generated by Django 5.2.3 on 2025-07-20 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0006_remove_actividad_meta_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparacionUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('total_usuarios_activos', models.IntegerField(default=0)),
                ('promedio_rendimiento_general', models.FloatField(default=0.0)),
                ('promedio_habitos_completados', models.FloatField(default=0.0)),
                ('promedio_tareas_completadas', models.FloatField(default=0.0)),
                ('top_usuarios', models.JSONField(default=list)),
                ('usuarios_mejorando', models.JSONField(default=list)),
                ('usuarios_necesitan_ayuda', models.JSONField(default=list)),
                ('tendencia_general', models.CharField(choices=[('positiva', 'Positiva'), ('estable', 'Estable'), ('negativa', 'Negativa')], default='estable', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('total_habitos', models.IntegerField(default=0)),
                ('total_tareas', models.IntegerField(default=0)),
                ('habitos_completados', models.IntegerField(default=0)),
                ('tareas_completadas', models.IntegerField(default=0)),
                ('rendimiento_habitos', models.FloatField(default=0.0)),
                ('rendimiento_tareas', models.FloatField(default=0.0)),
                ('rendimiento_general', models.FloatField(default=0.0)),
                ('dias_activo', models.IntegerField(default=0)),
                ('racha_actual', models.IntegerField(default=0)),
                ('mejor_racha', models.IntegerField(default=0)),
                ('habitos_bajo_rendimiento', models.JSONField(default=list)),
                ('habitos_mejorar', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_analisis'],
            },
        ),
        migrations.CreateModel(
            name='ReporteRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.TextField()),
                ('areas_mejora', models.JSONField(default=list)),
                ('logros', models.JSONField(default=list)),
                ('recomendaciones', models.JSONField(default=list)),
                ('puntuacion_general', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_generado'],
            },
        ),
        migrations.CreateModel(
            name='MetricaHabitual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_completados', models.IntegerField(default=0)),
                ('dias_totales', models.IntegerField(default=0)),
                ('porcentaje_completado', models.FloatField(default=0.0)),
                ('tendencia', models.CharField(choices=[('mejorando', 'Mejorando'), ('estable', 'Estable'), ('empeorando', 'Empeorando'), ('nuevo', 'Nuevo')], default='nuevo', max_length=20)),
                ('necesita_mejora', models.BooleanField(default=False)),
                ('recomendacion', models.TextField(blank=True, null=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_analytics.analisisusuario')),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.actividad')),
            ],
            options={
                'unique_together': {('analisis', 'habito')},
            },
        ),
    ]
